### ISSUE TITLE
Cosmetic enhancements to the Art Index Dashboard

### ISSUE THREAD

**Issue by kaljuvee** [kanvas-ai/artindex#6]
0/ Add hyperlink to Kanvas.ai Logo on top (to www.kanvas.ai)
Art Index (2001 - 2021) -> Estonian Art Index

try logos here:
https://drive.google.com/drive/folders/174eAdDKfiQatMOZlB8Sv0YTr477VRym4?usp=sharing

1/ Let's create an Estonian version, currently just use Google Translate (we'll review)
Page menu: 'EN' and 'EE' (and a link on Kanvas.ai if possible)

2/ Remove text 'Estonian Auctions - Map of Art Market', add Overview section on top instead:

https://docs.google.com/document/d/1Pf1maRaOWyxwj2xEz7SUhumOXzCvrx8j3dqu53rr3cM/edit

3/ Figure - Historical Price Performance
y-axis: Average Price (EUR) -> Historical Index Performance (EUR)
Table - Historical Price Performance -> Table - Historical Price Performance by Price Category
Oil paint -> Oil paintings
Other oil paint -> Other (non-oil) paintings
Other -> Mixed medium
3.5/ Figure - Historical Volume Growth
4/ Table - Historical Volume Growth -> Historical Volume Growth by Category
5/ Table - Top 10 Best Performing Artists - can we sort this by Total Return
6/ Table - Volume Growth for Top 10 Artists
Let's rename columns Total Return (%)-> Total Growth since Inception (%)
Annual Return (%)-> Annual Growth Rate (%)
Check the numbers - Volume table seems partially a copy of the price table
7/ Figure - Age of Art Work vs Price
End Price -> Auction Final Sales Price (EUR)
8/ Figure - Size of Art Work vs Price
Oil paint -> Oil paintings
Other oil paint -> Other (non-oil) paintings
Other -> Mixed medium
Display in square metres, so 0.4M -> 0.4m2
Astid Laupmaa -> Astrid
Source: Estonian Auctions > Estonian public art auction sales (2001-2021)

**Comment by markussulg** [comment]
Mostly done, remaining enhancements:

1. Let's create an Estonian version, currently just use Google Translate (we'll review)
Page menu: 'EN' and 'EE' (and a link on Kanvas.ai if possible)
1. Top 10 author tables - check the numbers - Volume table seems partially a copy of the price table
1. Fix dark mode logo and tables
